var countries = //europa ------------------------------------------------------------
                [["Albania", "3100_2435_2.5", "Macedonia", "Grecja", "Czarnogóra", "Serbia", "Kosowo"],
                ["Andora", "2835_2663_5.5", "Hiszpania", "Francja"],
                ["Austria", "3019_2762_1.5", "Szwajcaria", "Niemcy", "Węgry", "Słowacja", "Czechy", "Włochy", "Słowenia", "Liechtenstein"],
                ["Belgia", "2884_2822_2.5", "Niemcy", "Holandia", "Luksemburg", "Francja"],
                ["Białoruś", "3189_2879_1.3", "Polska", "Litwa", "Ukraina", "Rosja", "Łotwa"],
                ["Bośnia i Hercegowina", "3067_2694_2.5", "Chorwacja", "Czarnogóra", "Serbia"],
                ["Bułgaria", "3173_2664_2", "Macedonia", "Grecja", "Rumunia", "Turcja", "Serbia", "Morze Czarne"],
                ["Chorwacja", "3045_2725_2.5", "Węgry", "Bośnia i Hercegowina", "Czarnogóra", "Serbia", "Słowenia"],
                ["Czarnogóra", "3086_2668_2.5", "Albania", "Chorwacja", "Bośnia i Hercegowina", "Serbia", "Kosowo"],
                ["Czechy", "3029_2804_2.5", "Polska", "Niemcy", "Słowacja", "Austria"],
                ["Dania", "2945_2927_2.5", "Niemcy", "Morze Bałtyckie"],
                ["Estonia", "3150_2983_2.5", "Rosja", "Łotwa", "Morze Bałtyckie"],
                ["Finlandia", "3152_3111_1.3", "Norwegia", "Rosja", "Szwecja", "Morze Bałtyckie"],
                ["Francja", "2853_2740_1.3", "Szwajcaria", "Niemcy", "Belgia", "Luksemburg", "Włochy", "Andora", "Monako", "Hiszpania"],
                ["Grecja", "3129_2603_1.5", "Albania", "Macedonia", "Turcja", "Bułgaria"],
                ["Hiszpania", "2759_2620_1.3", "Andora", "Portugalia", "Gibraltar", "Francja", "Maroko"],
                ["Holandia", "2895_2850_2.5", "Niemcy", "Belgia"],
                ["Irlandia", "2722_2872_2", "Wielka Brytania"],
                ["Islandia", "2629_3105_1.5"],
                ["Kazachstan", "3741_2775_1", "Turkmenistan", "Chiny", "Kirgistan", "Uzbekistan", "Rosja"],
                ["Liechtenstein", "2949.5_2754.7_5.5", "Szwajcaria", "Austria"],
                ["Litwa", "3134_2915_2", "Polska", "Łotwa", "Białoruś", "Rosja", "Morze Bałtyckie"],
                ["Luksemburg", "2903_2805_4", "Belgia", "Niemcy", "Francja"],
                ["Łotwa", "3148_2946_2", "Litwa", "Estonia", "Białoruś", "Rosja", "Morze Bałtyckie"],
                ["Macedonia", "3123_2644_3", "Albania", "Grecja", "Bułgaria", "Serbia", "Kosowo"],
                ["Malta", "3020.8_2532.7_5"],
                ["Mołdawia", "3212_2754_2.5", "Rumunia", "Ukraina"],
                ["Monako", "2912_2683_3", "Francja"],
                ["Niemcy", "2962_2829_1.3", "Szwajcaria", "Polska", "Holandia", "Dania", "Belgia", "Czechy", "Luksemburg", "Francja", "Austria", "Morze Bałtyckie"],
                ["Norwegia", "2947_3029_1.3", "Finlandia", "Rosja", "Szwecja"],
                ["Polska", "3080_2851_1.3", "Niemcy", "Litwa", "Słowacja", "Czechy", "Białoruś", "Ukraina", "Rosja", "Morze Bałtyckie"],
                ["Portugalia", "2693_2605_1.5", "Hiszpania"],
                ["Rosja", "3591_3032_1", "Gruzja", "Chiny", "Białoruś", "Ukraina", "Kazachstan", "Łotwa", "Polska", "Estonia", "Litwa", "Finlandia", "Mongolia", "Norwegia", "Azerbejdżan", "Korea Północna", "Morze Bałtyckie", "Morze Czarne"],
                ["Rumunia", "3163_2726_1.3", "Mołdawia", "Węgry", "Ukraina", "Bułgaria", "Serbia", "Morze Czarne"],
                ["San Marino", "2990_2691_5", "Włochy"],
                ["Serbia", "3108_2694_2.3", "Albania", "Węgry", "Macedonia", "Rumunia", "Chorwacja", "Bośnia i Hercegowina", "Bułgaria"],
                ["Słowacja", "3086_2785_2.3", "Polska", "Węgry", "Czechy", "Ukraina", "Austria"],
                ["Słowenia", "3021_2731_3", "Węgry", "Włochy", "Chorwacja", "Austria"],
                ["Szwajcaria", "2931_2749_3", "Niemcy", "Włochy", "Liechtenstein", "Francja", "Austria"],
                ["Szwecja", "3014_3026_1.3", "Norwegia", "Finlandia", "Morze Bałtyckie"],
                ["Turcja", "3328_2595_1.3", "Syria", "Gruzja", "Irak", "Iran", "Grecja", "Armenia", "Azerbejdżan", "Bułgaria", "Morze Czarne"],
                ["Ukraina", "3220_2802_1.3", "Polska", "Mołdawia", "Węgry", "Słowacja", "Białoruś", "Rumunia", "Rosja", "Morze Czarne"],
                ["Watykan", "2992.6_2649_5", "Włochy"],
                ["Węgry", "3086_2752_1.5", "Słowacja", "Słowenia", "Rumunia", "Ukraina", "Chorwacja", "Austria", "Serbia"],
                ["Wielka Brytania", "2803_2870_1.3", "Irlandia"],
                ["Włochy", "2991_2672_1.3", "Szwajcaria", "Watykan", "Słowenia", "San Marino", "Francja", "Austria"],
                // azja --------------------------------------------------------------
                ["Afganistan", "3784_2493_1.3", "Chiny", "Iran", "Pakistan", "Tadżykistan", "Turkmenistan", "Uzbekistan"],
                ["Arabia Saudyjska", "3489_2292_1", "Katar", "Oman", "Irak", "Jamen", "Jordania", "Zjednoczone Emiraty Arabskie", "Kuwejt"],
                ["Armenia", "3452_2627_2.5", "Gruzja", "Iran", "Azerbejdżan", "Turcja"],
                ["Azerbejdżan", "3500_2626_2.5", "Gruzja", "Iran", "Armenia", "Turcja", "Rosja"],
                ["Bahrajn", "3580.3_2346_4"],
                ["Bangladesz", "4195_2317_1.3", "Myanmar", "Indie"],
                ["Bhutan", "4186_2386_2", "Chiny", "Indie"],
                ["Brunei", "4638_1919_2.5", "Malezja"],
                ["Chiny", "4315_2545_1", "Laos", "Bhutan", "Tadżykistan", "Kazachstan", "Mongolia", "Afganistan", "Nepal", "Myanmar", "Kirgistan", "Pakistan", "Korea Północna", "Rosja", "Wietnam", "Indie"],
                ["Cypr", "3299_2517_3"],
                ["Filipiny", "4753_2065_1.3"],
                ["Gruzja", "3432_2658_1.3", "Armenia", "Azerbejdżan", "Turcja", "Rosja", "Morze Czarne"],
                ["Indie", "4030_2266_1", "Chiny", "Nepal", "Myanmar", "Bhutan", "Pakistan", "Bangladesz"],
                ["Indonezja", "4634_1792_1", "Papua-Nowa Gwinea", "Timor Wschodni", "Malezja"],
                ["Irak", "3440_2484_1.3", "Syria", "Arabia Saudyjska", "Iran", "Jordania", "Turcja", "Kuwejt"],
                ["Iran", "3624_2472_1", "Turkmenistan", "Afganistan", "Irak", "Armenia", "Pakistan", "Azerbejdżan", "Turcja"],
                ["Izrael", "3332_2439_2.5", "Syria", "Jordania", "Liban", "Egipt", "Palestyna"],
                ["Japonia", "4823_2620_1.3"],
                ["Jemen", "3560_2136_1.3", "Arabia Saudyjska", "Oman"],
                ["Jordania", "3353_2437_2.5", "Syria", "Arabia Saudyjska", "Irak", "Izrael", "Palestyna"],
                ["Kambodża", "4474_2086_1.3", "Laos", "Tajlandia", "Wietnam"],
                ["Katar", "3591_2329_3", "Arabia Saudyjska"],
                //["Kazachstan", "", "Turkmenistan", "Chiny", "Kirgistan", "Uzbekistan", "Rosja"], ---> jest w krajach europejskich
                ["Kirgistan", "3881_2659_1.3", "Chiny", "Tadżykistan", "Uzbekistan", "Kazachstan"],
                ["Korea Południowa", "4674_2602_1.3", "Korea Północna"],
                ["Korea Północna", "4617_2682_1.3", "Chiny", "Rosja", "Korea Południowa"],
                ["Kuwejt", "3525.5_2409_2.5", "Arabia Saudyjska", "Irak"],
                ["Laos", "4407_2232_1.3", "Chiny", "Myanmar", "Kambodża", "Tajlandia", "Wietnam"],
                ["Liban", "3340_2495_2.5", "Syria", "Izrael"],
                //["Malediwy", "1389_452_2.5"], --------> brak na mapie
                ["Malezja", "4444_1888_1.3", "Brunei", "Tajlandia", "Indonezja"],
                ["Myanmar", "4299_2271_1.3", "Chiny", "Laos", "Tajlandia", "Bangladesz", "Indie"],
                ["Mongolia", "4228_2784_1", "Chiny", "Rosja"],
                ["Nepal", "4086_2396_1.3", "Chiny", "Indie"],
                ["Oman", "3678_2219_1.3", "Arabia Saudyjska", "Jemen", "Zjednoczone Emiraty Arabskie"],
                ["Pakistan", "3853_2417_1", "Chiny", "Afganistan", "Iran", "Indie"],
                ["Singapur", "4467_1853.5_7"],
                ["Sri Lanka", "4092_1978_1.3"],
                ["Syria", "3380_2514_1.3", "Irak", "Jordania", "Izrael", "Turcja", "Liban"],
                ["Tadżykistan", "3857_2599_1.3", "Chiny", "Afganistan", "Kirgistan", "Uzbekistan"],
                ["Tajlandia", "4401_2155_1.3", "Laos", "Myanmar", "Kambodża", "Malezja"],
                ["Timor Wschodni", "4812.5_1634_2.5", "Indonezja"],
                ["Turkmenistan", "3669_2607_1.3", "Afganistan", "Iran", "Uzbekistan", "Kazachstan"],
                ["Uzbekistan", "3718_2659_1.3", "Turkmenistan", "Afganistan", "Kirgistan", "Tadżykistan", "Kazachstan"],
                ["Wietnam", "4515_2068_1.3", "Chiny", "Laos", "Kambodża"],
                ["Zjednoczone Emiraty Arabskie", "3645_2294_2", "Arabia Saudyjska", "Oman"],
                // Australia i oceania ----------------------------------------------------------
                ["Australia", "4870_1260_0.5"],
                ["Fidżi", "5588_1393_0.8"],
                ["Mikronezja", "5415_1949_1.2"],
                ["Nowa Kaledonia", "5366_1327_1.2"],
                ["Nowa Zelandia", "5157_831_0.8"],
                ["Papua-Nowa Gwinea", "5112_1683_0.8", "Indonezja"],
                ["Vanuatu", "5435_1464_1.2"],
                ["Wyspy Marshalla", "5543.6_1995_1.2"],
                ["Wyspy Salomona", "5358_1601.5_0.8"],
                // za małe i niewidoczne na mapie
                //["Kiribati", ""],
                //["Nauru", ""],
                //["Palau", ""],
                //["Samoa", ""],
                //["Tonga", ""],
                //["Tuvalu", ""],
                // Afryka -------------------------------------------------------------------------
                ["Algieria", "2852_2359_1", "Niger", "Sahara Zachodnia", "Libia", "Mauretania", "Tunezja", "Maroko", "Mali"],
                ["Angola", "3077_1571_1", "Demokratyczna Republika Kongo", "Namibia", "Zambia", "Republika Kongo"],
                ["Benin", "2830_2010_1", "Niger", "Togo", "Burkina Faso", "Nigeria"],
                ["Botswana", "3177_1386_1", "Zimbabwe", "Republika Południowej Afryki", "Namibia"],
                ["Burkina Faso", "2774_2070_1", "Niger", "Benin", "Ghana", "Wybrzeże Kości Słoniowej", "Togo", "Mali"],
                ["Burundi", "3275_1758.5_1.3", "Tanzania", "Demokratyczna Republika Kongo", "Rwanda"],
                ["Czad", "3094_2122_1", "Niger", "Libia", "Republika Środkowoafrykańska", "Sudan", "Kamerun", "Nigeria"],
                ["Demokratyczna Republika Kongo", "3173_1772_1", "Tanzania", "Republika Środkowoafrykańska", "Sudan Południowy", "Rwanda", "Zambia", "Burundi", "Uganda", "Republika Kongo", "Angola"],
                ["Dżibuti", "3473_2058_1.3", "Erytrea", "Etiopia", "Somalia"],
                ["Egipt", "3255_2342_1", "Libia", "Sudan", "Izrael", "Palestyna"],
                ["Erytrea", "3399_2136_1", "Etiopia", "Sudan", "Dżibuti"],
                ["Etiopia", "3429_2000_1", "Erytrea", "Kenia", "Sudan", "Sudan Południowy", "Somalia", "Dżibuti"],
                ["Gabon", "2987_1813_1", "Kamerun", "Gwinea Równikowa", "Republika Kongo"],
                ["Gambia", "2553_2094.7_3", "Senegal"],
                ["Ghana", "2770_1975_1", "Wybrzeże Kości Słoniowej", "Togo", "Burkina Faso"],
                ["Gwinea", "2621_2037_1", "Liberia", "Senegal", "Sierra Leone", "Wybrzeże Kości Słoniowej", "Gwinea Bissau", "Mali"],
                ["Gwinea Bissau", "2560_2063_1.3", "Gwinea", "Senegal"],
                ["Gwinea Równikowa", "2963_1855_1.3", "Gabon", "Kamerun"],
                ["Kamerun", "2995_1918_1", "Czad", "Republika Środkowoafrykańska", "Gabon", "Gwinea Równikowa", "Republika Kongo", "Nigeria"],
                ["Kenia", "3399_1835_1", "Etiopia", "Tanzania", "Sudan Południowy", "Somalia", "Uganda"],
                ["Komory", "3488_1593_3"],
                ["Republika Kongo", "3046_1801_1", "Republika Środkowoafrykańska", "Gabon", "Demokratyczna Republika Kongo", "Kamerun", "Angola"],
                ["Lesotho", "3232_1238_2", "Republika Południowej Afryki"],
                ["Liberia", "2645_1947_1", "Sierra Leone", "Wybrzeże Kości Słoniowej", "Gwinea"],
                ["Libia", "3066_2347_1", "Czad", "Niger", "Algieria", "Sudan", "Tunezja", "Egipt"],
                ["Madagaskar", "3532_1437_1"],
                ["Malawi", "3334_1556_1.3", "Tanzania", "Mozambik", "Zambia"],
                ["Mali", "2774_2170_1", "Senegal", "Niger", "Algieria", "Wybrzeże Kości Słoniowej", "Gwinea", "Mauretania", "Burkina Faso"],
                ["Maroko", "2704_2447_1", "Algieria", "Sahara Zachodnia", "Hiszpania"],
                ["Mauretania", "2626_2211_1", "Senegal", "Algieria", "Sahara Zachodnia", "Mali"],
                ["Mauritius", "3702_1416.6_2"],
                ["Mozambik", "3356_1469_1", "Zimbabwe", "Tanzania", "Suazi", "Republika Południowej Afryki", "Zambia", "Malawi"],
                ["Namibia", "3066_1376_1", "Republika Południowej Afryki", "Botswana", "Zambia", "Angola"],
                ["Niger", "2945_2162_1", "Czad", "Benin", "Algieria", "Libia", "Burkina Faso", "Nigeria", "Mali"],
                ["Nigeria", "2924_1997_1", "Czad", "Niger", "Benin", "Kamerun"],
                ["Republika Południowej Afryki", "3169_1248_1", "Zimbabwe", "Suazi", "Mozambik", "Botswana", "Namibia", "Lesotho"],
                ["Republika Środkowoafrykańska", "3128_1954_1", "Czad", "Sudan", "Demokratyczna Republika Kongo", "Sudan Południowy", "Kamerun", "Republika Kongo"],
                ["Wyspy Zielonego Przylądka", "2420.8_2124.6_2"],
                ["Rwanda", "3275_1784_1.3", "Tanzania", "Demokratyczna Republika Kongo", "Burundi", "Uganda"],
                ["Senegal", "2569_2106_1", "Gwinea", "Mauretania", "Gwinea Bissau", "Gambia", "Mali"],
                ["Seszele", "3687_1733_1.3"],
                ["Sierra Leone", "2607_1992.6_1", "Liberia", "Gwinea"],
                ["Somalia", "3530_1901_1", "Etiopia", "Kenia", "Dżibuti"],
                ["Suazi", "3286_1299_1.3", "Republika Południowej Afryki", "Mozambik"],
                ["Sudan", "3266_2141_1", "Sudan Południowy", "Czad", "Egipt", "Etiopia", "Erytrea", "Libia", "Republika Środkowoafrykańska"],
                ["Sudan Południowy", "3288_1961_1", "Demokratyczna Republika Kongo", "Republika Środkowoafrykańska", "Etiopia", "Kenia", "Sudan", "Uganda"],
                ["Tanzania", "3362_1700_1", "Mozambik", "Kenia", "Demokratyczna Republika Kongo", "Rwanda", "Zambia", "Burundi", "Uganda", "Malawi"],
                ["Togo", "2812_1988_1.3", "Benin", "Ghana", "Burkina Faso"],
                ["Tunezja", "2943_2496_1.3", "Algieria", "Libia"],
                ["Uganda", "3308_1845_1.3", "Tanzania", "Kenia", "Sudan Południowy", "Demokratyczna Republika Kongo", "Rwanda"],
                ["Wybrzeże Kości Słoniowej", "2703_1975_1.3", "Liberia", "Ghana", "Gwinea", "Burkina Faso", "Mali"],
                ["Wyspy Świętego Tomasza i Książęca", "2900_1830_2"],
                ["Zambia", "3231_1536_1", "Zimbabwe", "Tanzania", "Mozambik", "Demokratyczna Republika Kongo", "Namibia", "Malawi", "Angola"],
                ["Zimbabwe", "3266_1448_1", "Republika Południowej Afryki", "Mozambik", "Botswana"],
                // Ameryka (Północna i Południowa) ------------------------------------------------
                //["Antigua i Barbua", ""],
                ["Argentyna", "633_208_1", "Chile", "Boliwia", "Urugwaj", "Paragwaj", "Brazylia"],
                ["Bahamy", "550_585_2"],
                ["Barbados", "644_512.5_2"],
                ["Belize", "484.5_537_1.3", "Gwatemala", "Meksyk"],
                ["Boliwia", "616_321_1", "Peru", "Chile", "Paragwaj", "Brazylia", "Argentyna"],
                ["Brazylia", "685_366_1", "Surinam", "Peru", "Boliwia", "Urugwaj", "Gujana", "Paragwaj", "Gujana Francuska", "Wenezuela", "Kolumbia", "Argentyna"],
                ["Chile", "599_210_1", "Peru", "Boliwia", "Argentyna"],
                ["Dominika", "635.5_527_2"],
                ["Dominikana", "587_450_2", "Haiti"],
                ["Ekwador", "537_420_1", "Peru", "Kolumbia"],
                ["Grenada", "632_506_2"],
                ["Gujana", "646_458_1.3", "Surinam", "Brazylia", "Wenezuela"],
                ["Gujana Francuska", "678_453_1.3", "Surinam", "Brazylia"],
                ["Gwatemala", "474_525_1.3", "Meksyk", "Honduras", "Belize", "Salwador"],
                ["Haiti", "577_550_2", "Dominikana"],
                ["Honduras", "494_523_1.3", "Gwatemala", "Nikaragua", "Salwador"],
                ["Jamajka", "548_544_2"],
                ["Kanada", "485_796_1", "Stany Zjednoczone"],
                ["Kolumbia", "567_451_1", "Ekwador", "Peru", "Panama", "Brazylia", "Wenezuela"],
                ["Kostaryka", "507_492_2", "Panama", "Nikaragua"],
                ["Kuba", "547_566_1.3"],
                ["Meksyk", "415_574_1", "Gwatemala", "Stany Zjednoczone", "Belize"],
                ["Nikaragua", "502_508_1.3", "Kostaryka", "Honduras"],
                ["Panama", "523_481_1.3", "Kostaryka", "Kolumbia"],
                ["Paragwaj", "656_280_1", "Boliwia", "Brazylia", "Argentyna"],
                ["Peru", "551_373_1", "Ekwador", "Chile", "Boliwia", "Brazylia", "Kolumbia"],
                //["Saint Pierre i Miquelon", ""],
                ["Saint Lucia", "637_517_2"],
                ["Saint Vincent i Grenadyny", "635_513_2"],
                ["Salwador", "481_516_1.3", "Gwatemala", "Honduras"],
                ["Stany Zjednoczone", "441_678_1", "Kanada", "Meksyk"],
                ["Surinam", "662_455_1.3", "Gujana", "Brazylia", "Gujana Francuska"],
                ["Trynidad i Tobago", "634_495_2"],
                ["Urugwaj", "677_219_1.3", "Brazylia", "Argentyna"],
                ["Wenezuela", "610_475_1", "Gujana", "Brazylia", "Kolumbia"]
            ];

var seas = [
    //ocean Spokojny
            ["Morze Arafura", "1752_359_1.3", "Indonezja", "Austria", "Morze Koralowe", "Morze Timor", "Morze Seram", "Ocean Spokojny", "Ocean Indyjski"],
            ["Morze Balijskie", "1629_385_1.3", "Indonezja", "Ocean Spokojny", "Ocean Indyjski"],
            ["Morze Beringa", "189_818_1.3", "Stany Zjednoczone", "Rosja", "Ocean Spokojny"],
            ["Morze Bismarcka", "1809_405_1.3", "Papua-Nowa Gwinea", "Morze Salomona", "Ocean Spokojny"],
            ["Morze Celebes", "1660_452_1.3", "Filipiny", "Indonezja", "Malezja", "Morze Jawajskie", "Morze Flores", "Morze Sulu", "Morze Moluckie", "Ocean Spokojny"],
    ["Morze Bałtyckie", "1063_789_1.3", "Szwecja", "Finlandia", "Rosja", "Estonia", "Łotwa", "Litwa", "Polska", "Niemcy", "Dania", "Morze Północne", "Ocean Atlantycki"],
            ["Morze Czarne", "1151_703_1.3", "Bułgaria", "Gruzja", "Rosja", "Rumunia", "Turcja", "Ukraina", " Morze Azowskie", "Morze Marmara", "Ocean Atlantycki"]
            ];
var oceans = [
            ["Ocean Spokojny", "1995_623_0.3", "Morze Arafura", "Morze Balijskie", "Morze Beringa", "Morze Bismarcka", "Morze Celebes", "Morze Fidżi", "Morze Filipińskie", "Morze Flores", "Morze Halmahera", "Morze Japońskie", "Morze Jawajskie", "Morze Koralowe", "Morze Moluckie", "Morze Ochockie", "Morze Południowochińskie", "Morze Salomona", "Morze Sawu", "Morze Seram", "Morze Sulu", "Morze Tasmana", "Morze Wewnętrzne", "Morze Wschodniochińskie", "Morze Żółte"],
             ["Ocean Atlantycki", "761_589_0.3", "Morze Adriatyckie", "Morze Alandzkie", "Morze Alborańskie", "Morze Archipelagowe", "Morze Azowskie", "Morze Belearskie", "Morze Bałtyckie", "Morze Celtyckie", "Morze Czarne", "Morze Egejskie", "Morze Hebrydzkie", "Morze Irlandzkie", "Morze Jońskie", "Morze Karaibskie", "Morze Kreteńskie", "Morze Labradorskie", "Morze Liguryjskie", "Morze Marmara", "Morze Mirtejskie", "Morze Norweskie", "Morze Północne", "Morze Sargassowe", "Morze Scotia", "Morze Szkockie", "Morze Śródziemne", "Morze Trackie", "Morze Tyrreńskie", "Morze Wattowe"],
             ["Ocean Indyjski", "1419_359_0.3", "Morze Andamańskie", "Morze Arabskie", "Morze Czerwone", "Morze Lakkadiwskie", "Morze Timor"],
             ["Ocean Arktyczny", "1104_940_0.4", "Morze Baffina", "Morze Barentsa", "Morze Beauforta", "Morze Białe", "Morze Czukockie", "Morze Grenlandzkie", "Morze Karskie", "Morze Lincolna", "Morze Łaptiewów", "Morze Peczorskie", "Morze Wandela", "Morze Wschodniosyberyjskie"],
             //chyba bez oceanu południowego, bo tam i tak nic ciekawego nie ma
             ["Ocean Południowy", "1027_20_0.4", "Morze Amundsena", "Morze Bellingshausena", "Morze Davisa", "Morze Dumont d'Urville'a", "Morze Kosmonautów", "Morze Króla Haakona VII", "Morze Łazariewa", "Morze Mawsona", "Morze Riiser-Larsena", "Morze Rossa", "Morze Scotia", "Morze Somowa", "Morze Weddella", "Morze Wspólnoty"]
             ];
